name: stash_moor
version: 1.0.0-dev.3
description: >-
  Moor storage extension for the stash caching API. Provides support to store caches
  in a moor database in binary format using the msgpack json format
homepage: https://github.com/ivoleitao/stash_moor

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  moor: ^3.2.0
  stash: ^1.0.0-dev.2
  #stash:
  #  path: ../stash

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.1
  test_coverage: ^0.4.3
  build_runner: ^1.10.0
  build_verify: ^1.1.1
  moor_ffi: ^0.7.0
  moor_generator: ^3.2.0
