name: stash_moor
version: 1.0.0-dev.1
description: >-
  Moor storage extension for the stash caching API. Provides support to store caches
  in a moor database in binary format using the msgpack json format
homepage: https://github.com/ivoleitao/stash_moor

environment:
  sdk: ">=2.8.4 <3.0.0"

dependencies:
  moor: ^3.1.0
  stash:
    path: ../stash

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.1
  test_coverage: ^0.4.1
  build_runner: ^1.10.0
  build_verify: ^1.1.1
  moor_ffi: ^0.6.0
  moor_generator: ^3.1.0
